### ISSUE TITLE
[BUG] initialPromise is not a function

### ISSUE THREAD

**Issue by Minus10Degrees** [wavesplatform/waveskeeper-types#3]
**Describe the bug**
https://github.com/wavesplatform/waveskeeper-types/blob/44fe1b5b243d5dbb96858228c2bf9fc876d9831c/globals.d.ts#L136-L140

`initialPromise` is defined as a function, but in WavesKeeper it is an attribute.

**To Reproduce**
1. Create a new React project
2. Add `@waves/waveskeeper-types`
3. call initialPromise according to currently defined types:
```javascript
window.WavesKeeper.initialPromise().then(
      (res: WavesKeeper.TWavesKeeperApi) => { console.log(res); }
);
```

**Expected behavior**
Promise is resolved correctly

**Current behavior**
An error occurs:
`TypeError: window.WavesKeeper.initialPromise is not a function`

**Desktop:**
 - OS: Ubuntu 20.04.2 LTS
 - Tested on:
   - Firefox(v. 89.0.2, WavesKeeper v. 1.2.1) 
   - Chrome(v. 91.0.4472.114, WavesKeeper v. 1.2.2)

**Comment by smelnikov** [comment]
Thanks, fixed #4
